// coffeeScript.coffee: Generated by CoffeeScript 2.3.1 (coffeescript.coffee IMMED5 affects ./coffee -v)
(function() {
  // process: ENV={"node":true,"rn":false,"ut":true,"source":"/Users/pete/gitlab/rn/API/Flexbase/Date.coffee"}
  var EXPORTED, MMSS, N, NODE_util, O, dateTimeHyphenated, fs, trace;

  /*
  Date - Date functions					*** PROJECT AGNOSTIC ***

  WHAT: Node module

  DESCRIPTION

  FEATURES
  -

  NOTES
  -

  TODOs
  - UT		#H

  KNOWN BUGS:
  -
  */
  //if node
  fs = require('fs');

  NODE_util = require('util');

  //elseif rn
  //endif

  //import N
  N = require('./N');

  //import O
  O = require('./O');

  //import trace
  trace = require('./trace');

  dateTimeHyphenated = function() {
    var dd, mm, today, yyyy;
    today = new Date;
    dd = today.getDate();
    mm = today.getMonth() + 1;
    yyyy = today.getFullYear();
    if (dd < 10) {
      dd = '0' + dd;
    }
    if (mm < 10) {
      mm = '0' + mm;
    }
    return `${yyyy}-${mm}-${dd} ${N.ZEROPAD(today.getHours(), 2)}-${N.ZEROPAD(today.getMinutes(), 2)}-${N.ZEROPAD(today.getSeconds(), 2)}`;
  };

  MMSS = function() {
    var date;
    return `${N.ZEROPAD((date = new Date).getMinutes(), 2)}:${N.ZEROPAD(date.getSeconds(), 2)}`;
  };

  EXPORTED = {
    dateTimeHyphenated: dateTimeHyphenated,
    MMSS: MMSS,
    //if ut
    s_ut: function() {
      var Date_UT, UT;
      UT = require('./UT');
      return (new (Date_UT = class Date_UT extends UT {
        run() {
          return this.t("MMSS", function(ut) {
            return this.log(`MMSS: ${MMSS()}`);
          });
        }

      })).run();
    }
  };

  //endif
  module.exports = EXPORTED;

}).call(this);
