// coffeescript.js: Generated by CoffeeScript GITLAB/lib 2.3.0
var O, lg, log, process, trace;

O = require('./O');

trace = require('./trace');

log = function(line) {
  return process.stdout.write(line + '\n');
};

log = function(line) {
  return console.log(line + '\n');
};

lg = function(line) {
  return console.log(line);
};

process = function(code, ENV = {}) {
  var a, arg, i, len, line, lineNbr, lines, name, req, stack;
  //	log "process: ENV=#{JSON.stringify ENV}"
  code = code.toString();
  //	log "FILE: SRC1: #{code}\n"
  a = [];
  stack = [];
  name = null;
  arg = function(line) {
    var tokens;
    tokens = line.split(' ');
    //		log "arg: #{tokens[1]}"
    return tokens[1];
  };
  req = {
    bGo: true
  };
  lines = code.split('\n');
  for (lineNbr = i = 0, len = lines.length; i < len; lineNbr = ++i) {
    line = lines[lineNbr];
    //		line = line.replace /Charles/, 'Christmas'
    lg(`${lineNbr} LINE: ${line}`);
    switch (false) {
      case line.slice(0, 3) !== "#if":
        //				log "IF: line=#{line}: #{req.bGo}"

        // save current requirements for later
        stack.push(req);
        // clone (otherwise side offect of messing with requirements object just saved)
        req = Object.assign({}, req);
        // the default is that this #if section is DEAD.  BUT, if bGo is true, then not dead: we need to flip when it else
        req.bFlipOnElse = false;
        if (req.bGo) {
          req.bFlipOnElse = true;
          req.bFoundIF = true;
          name = arg(line);
          // only go if this target is one of the environments
          req.bGo = !!ENV[name];
        }
        break;
      //					log "IF: name=#{name} bGo=#{req.bGo}"
      case line.slice(0, 5) !== "#else":
        if (!req.bFoundIF) {
          throw new Error(`line=${lineNbr + 1} #else without #if`);
        }
        if (req.bFlipOnElse) {
          // we're alive, so flip... whatever the logic was, now it's the opposite
          //					log "flipping"
          req.bGo = !req.bGo;
        }
        break;
      case line.slice(0, 6) !== "#endif":
        req = stack.pop();
        break;
      default:
        if (req.bGo) {
          a.push(line);
        }
    }
  }
  return a.join('\n');
};

module.exports = {
  //if ut
  s_ut: function() {
    var PeterUT, UT;
    UT = require('./UT');
    return (new (PeterUT = class PeterUT extends UT {
      run() {
        return this.s("process", function() {
          var fn;
          fn = (c1, c2, ENV, that) => {
            var rv;
            //						console.log "====================BEFORE================ ENV=#{JSON.stringify ENV}"
            //						console.log c1
            //						console.log "-----------------------------------------------"
            //						console.log c2
            //						console.log "-----------------------------------------------"
            rv = process(c1, ENV);
            return that.eq(rv, c2);
          };
          this.t("trivial", function() {
            var c1, c2;
            c1 = "abc\ndef";
            c2 = "abc\ndef";
            return fn(c1, c2, {}, this);
          });
          this.t("if: env=", function() {
            var c1, c2;
            c1 = "before\n#if rn\nthis is rn\n#else\nthis is NOT rn\n#endif\nafter";
            c2 = "before\nthis is NOT rn\nafter";
            return fn(c1, c2, {}, this);
          });
          this.t("if: env=rn", function() {
            var c1, c2;
            c1 = "before\n#if rn\nthis is rn\n#else\nthis is NOT rn\n#endif\nafter";
            c2 = "before\nthis is rn\nafter";
            return fn(c1, c2, {
              rn: true
            }, this);
          });
          this.t("nested if: env=emily", function() {
            var c1, c2;
            c1 = "before\n#if rn\nthis is rn\n#else\nthis is NOT rn\n#if emily\nthis is emily\n#else\nthis is NOT emily\n#endif\n#endif\nafter";
            c2 = "before\nthis is NOT rn\nthis is emily\nafter";
            return fn(c1, c2, {
              emily: true
            }, this);
          });
          return this.T("#else", {
            expect: "EXCEPTION"
          }, function() {
            var c1, c2;
            c1 = "abc\n#else\ndef";
            c2 = "abc3\ndef";
            return fn(c1, c2, {
              rn: true
            }, this);
          });
        });
      }

    })).run();
  },
  //endif
  process: process
};
