// coffeeScript.coffee: Generated by CoffeeScript 2.3.1 (coffeescript.coffee IMMEDIATELY3 affects ./coffee -v)
var bUnitTest, c, fn, target;

bUnitTest = 66;

c = "Charles!";

target = "rn2";

fn = function(a) {
  var i, len, results, v;
  results = [];
  for (i = 0, len = a.length; i < len; i++) {
    v = a[i];
    results.push(v);
  }
  return results; //R
};
